### ISSUE TITLE
EventTarget MaxListenersExceededWarning

### ISSUE THREAD

**Issue by zquestz** [jliuhtonen/blu-hawaii#91] opened 2024-09-18 19:19 UTC
Seeing the following in my logs. 

date,stream,content
2024/09/18 09:14:59,stdout,(node:1) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase limit

Can we set the default a little higher? It defaults to 10 but my setup is a little larger.

**Comment by jliuhtonen** [comment] 2024-09-19 17:05
I noticed the same. This seems to be because of a problem in Node's native fetch-api implementation undici: https://github.com/nodejs/undici/issues/1711

If you are using the Docker container, then you have an old version. I'll update Node to latest LTS version, let's see if the problem goes away with that. Otherwise, this could be a subtle bug in the cancellation/retry code.

**Comment by jliuhtonen** [comment] 2024-09-19 17:24
Version [1.2.1](https://github.com/jliuhtonen/blu-hawaii/releases/tag/v1.2.1) released!

**Comment by zquestz** [comment] 2024-09-19 21:35
Unfortunately I am still seeing the issue in my logs.

**Comment by jliuhtonen** [comment] 2024-09-20 09:15
Thanks for reporting this. Back to the drawing board then!

This might be related to for example long polling BluOS players. However, before increasing the amount of maximum listeners I'd like to make sure that the current request cancellation implementation or the fetch api wrapper library do not leak listeners, because the error message would be exactly the same.

**Comment by zquestz** [comment] 2024-09-21 20:18
Absolutely, take your time. Makes sense to find the root cause and not mask real errors. =)

**Comment by jliuhtonen** [comment] 2024-09-26 18:49
I released a new version v1.3.0 with a bugfix for cancellation using AbortSignal. Can you try that @zquestz? You can also try running with `DEBUG_MAX_EVENT_LISTENERS=<number>` env variable but I don't recommend changing the value if absolutely not necessary as the default value should work ok.

**Comment by zquestz** [comment] 2024-09-26 21:00
I have updated to the latest release and will get back to you. 😀

**Comment by zquestz** [comment] 2024-09-26 22:02
Unfortunately I am seeing the log warnings with the latest release. =\

Should I try updating that ENV var?

**Comment by jliuhtonen** [comment] 2024-09-27 05:21
> Should I try updating that ENV var?

Yes, that'd be great!

**Comment by jliuhtonen** [comment] 2024-09-27 12:19
@zquestz I noted that there's something wrong with scrobbling in the latest release. I'll release a patch release once I've had chance to fix.

**Comment by jliuhtonen** [comment] 2024-09-27 15:17
v1.3.1 fixes accidentally broken long polling. Sorry about that. Please provide any additional information that you can find @zquestz, this is a difficult issue to reproduce with my setup.

**Comment by zquestz** [comment] 2024-09-30 00:28
Still seeing the exact same error:

```
(node:1) MaxListenersExceededWarning: Possible EventTarget memory leak detected. 11 abort listeners added to [AbortSignal]. Use events.setMaxListeners() to increase limit
```

Odd thing is that I have DEBUG_MAX_EVENT_LISTENERS set to 30!

**Comment by jliuhtonen** [comment] 2024-10-01 18:09
> Still seeing the exact same error:
> 
> Odd thing is that I have `DEBUG_MAX_EVENT_LISTENERS` set to 30!

This is really weird. Practically it would mean that event listeners are leaking that would eventually cause the out of memory killer to stop the container so you would see crashing. I could try to run a profiler to see how the memory footprint develops over time.

If you are not seeing a memory leak, it means that Node's undici still produces this warning for some reason but it is harmless. I guess you have double checked already that you have the latest container?

One could also switch away from using fetch API, but as it is becoming the standard in Node it does not seem worth it.

**Comment by zquestz** [comment] 2024-10-01 21:47
You were totally right, updating the image on my Synology and restarting the container was not enough to get the new version. It is now updated and testing continues. =)

**Comment by zquestz** [comment] 2024-10-02 01:34
All appears to be working fantastic now. =)

**Comment by jliuhtonen** [comment] 2024-10-03 04:01
> You were totally right, updating the image on my Synology and restarting the container was not enough to get the new version. It is now updated and testing continues. =)

Great to hear that it works now! I have run into something similar when updating images locally. Cache invalidation, the hardest of problems. 😂 The new releases are tagged with both the version number and "latest".

Let's keep this issue still open for a little while if something still comes up related to this.

**Comment by jliuhtonen** [comment] 2024-10-05 07:13
Everything seems to be working, so I'm closing this issue for now. Thank you for helping to make the project better! 🙏

**Comment by zquestz** [comment] 2024-10-05 07:14
My pleasure. Thanks for all the help!

**Closed by jliuhtonen** 2024-10-05 07:13 UTC
Labels: bug
